version: '3.9'

services:
  jupyterlab:
    container_name: jupyterlab
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./src:/src
    command:
      jupyter-lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --no-browser
